### ISSUE TITLE
Data Bars Questions

### ISSUE THREAD

**Issue by dn4086** [jdharrisnz/datorama-d3-data-bars-table#1]
![image](https://user-images.githubusercontent.com/82388743/178833132-e37c0fda-bd2f-4d21-97a7-188abb15c151.png)

Hi Josh
Is there a way to populate rows that we do not have data for? For example in the image we don't have data for Q1 and Q4, but would like to know whether we can have Q1 and Q4 but just populate it with Zeros.

**Comment by jdharrisnz** [comment]
Hi Dan, thanks for continuing to use these. While technically possible, it would be a weird feature for a table visualisation, as you’d only expect one row to show up for each row in the data.

I think you could make this work in a hacky way by uploading $0.001 of spend data for one day in each quarter. It would round to zero but should cause rows to show up.
